spring.application.name=citoyensArmes

server.port=${SERVER_PORT:8080}
# Configuration MongoDB NoSQL
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/citoyens_armes}

# Configuration des logs
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=TRACE
logging.level.fr.limoges.valadon.btssio.citoyensarmes=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
